### ISSUE TITLE
github.com/tencentyun/vod-go-sdk@v1.0.0/client.go:151:5: cannot use int(stat.Size()) (type int) as type int64 in field value

### ISSUE THREAD

**Issue by congfengzhang** [tencentyun/vod-go-sdk#6]
github.com/tencentyun/vod-go-sdk@v1.0.0/client.go:151:5: cannot use int(stat.Size()) (type int) as type int64 in field value

**Comment by congfengzhang** [comment]
这个bug我看master已经修复了，求新建一个tag

**Comment by soulhdb** [comment]
done
